"""LangGraph state schema for salary estimation."""

from typing import Annotated, TypedDict
from operator import add

from salary_estimator.models import ProfileData, SalaryRange, SalaryBenchmark, SearchResult


def replace_value(existing: any, new: any) -> any:
    """Reducer that replaces the existing value with the new one."""
    return new


class SalaryEstimationState(TypedDict, total=False):
    """State schema for the salary estimation graph.

    This defines all the data that flows through the LangGraph workflow.
    """

    # Input - the raw LinkedIn profile text
    raw_profile: str

    # Extracted profile data from profile_parser node
    profile: Annotated[ProfileData | None, replace_value]

    # Search queries generated by query_generator node
    search_queries: Annotated[list[str], replace_value]

    # Web search results from web_searcher node
    search_results: Annotated[list[SearchResult], add]

    # Knowledge base matches from knowledge_lookup node
    kb_matches: Annotated[list[SalaryBenchmark], replace_value]

    # Final estimation outputs from salary_analyzer node
    salary_estimate: Annotated[SalaryRange | None, replace_value]
    confidence_score: Annotated[float, replace_value]
    reasoning: Annotated[str, replace_value]
    sources: Annotated[list[str], replace_value]
    adjustments: Annotated[list[str], replace_value]

    # Final structured response
    final_response: Annotated[dict, replace_value]
